name: Continuous integration

on:
  push:
    branches-ignore:
      - documentation
  pull_request:
    branches-ignore:
      - documentation

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone Repository
        uses: actions/checkout@v3

      - name: Build, Test and Coverage
        uses: danielTobon43/PCL-Build-Action@testing
        with:
          build_tests: true
          build_coverage: true

      - name: Install LCOV
        run: sudo apt-get update && sudo apt-get -y install lcov

      - name: LCOV Minimum coverage checker
        uses: terencetcf/github-actions-lcov-minimum-coverage-checker@v1
        with:
          coverage-file: coverage.info
