name: Continuous integration

on:
  push:
    branches-ignore:
      - documentation
  pull_request:
    branches-ignore:
      - documentation

jobs:
  build-and-test:
    runs-on: ubuntu-20.04

    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: PCL Build Action
        uses: danielTobon43/PCL-CMake-Action@v1
